"""initial schema

Revision ID: 2835a8e45876
Revises: 
Create Date: 2026-06-17 01:55:53.839563

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2835a8e45876'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('daily_revenue',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('total_orders', sa.BigInteger(), nullable=False),
    sa.Column('total_revenue', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('total_refunds', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('net_revenue', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('date')
    )
    op.create_table('customer_metrics',
    sa.Column('customer_id', sa.BigInteger(), nullable=False),
    sa.Column('order_count', sa.BigInteger(), nullable=False),
    sa.Column('total_spend', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('customer_id')
    )
    op.create_index('ix_customer_metrics_total_spend_desc', 'customer_metrics', ['total_spend'], unique=False, postgresql_ops={'total_spend': 'DESC'})
    op.create_table('orders',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('customer_id', sa.BigInteger(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_orders_created_at', 'orders', ['created_at'], unique=False)
    op.create_index('ix_orders_customer_id', 'orders', ['customer_id'], unique=False)
    op.create_index('ix_orders_customer_id_created_at', 'orders', ['customer_id', 'created_at'], unique=False)
    op.create_table('refunds',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('order_id', sa.BigInteger(), nullable=False),
    sa.Column('refund_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_refunds_created_at', 'refunds', ['created_at'], unique=False)
    op.create_index('ix_refunds_order_id', 'refunds', ['order_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_refunds_order_id', table_name='refunds')
    op.drop_index('ix_refunds_created_at', table_name='refunds')
    op.drop_table('refunds')
    op.drop_index('ix_orders_customer_id_created_at', table_name='orders')
    op.drop_index('ix_orders_customer_id', table_name='orders')
    op.drop_index('ix_orders_created_at', table_name='orders')
    op.drop_table('orders')
    op.drop_index('ix_customer_metrics_total_spend_desc', table_name='customer_metrics', postgresql_ops={'total_spend': 'DESC'})
    op.drop_table('customer_metrics')
    op.drop_table('daily_revenue')
    op.drop_table('customers')
    # ### end Alembic commands ###
